### ISSUE TITLE
Video Download problem 

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#1089]
### Steps to reproduce

Video download is not working until it play. When I'm trying to download a movie by holding the download button or choosing download mirror option, it's just loading until I end. But when I play the video and all the links successfully load, then I try to download again now it's work fine. All the links shows. 

### Expected behavior

Holding the download button or choosing download mirror option should show the all download mirror links.
There is no option to select maximum download at a time. 

### Actual behavior

It's just loading until the video play and load all the links. 

### Cloudstream version and commit hash

4.3.2 ee4d1de May 9, 2024 7:48:07 PM 

### Android version

Android 12

### Logcat

```java
--------- beginning of crash
05-13 02:55:17.684 23959 23959 E AndroidRuntime: FATAL EXCEPTION: main
05-13 02:55:17.684 23959 23959 E AndroidRuntime: Process: com.lagradost.cloudstream3.prerelease, PID: 23959
05-13 02:55:17.684 23959 23959 E AndroidRuntime: android.view.InflateException: Binary XML file line #59 in com.lagradost.cloudstream3.prerelease:layout/home_result_grid_expanded: Binary XML file line #59 in com.lagradost.cloudstream3.prerelease:layout/home_result_grid_expanded: Error inflating class <unknown>
05-13 02:55:17.684 23959 23959 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #59 in com.lagradost.cloudstream3.prerelease:layout/home_result_grid_expanded: Error inflating class <unknown>
05-13 02:55:17.684 23959 23959 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.lagradost.cloudstream3.databinding.HomeResultGridExpandedBinding.inflate(HomeResultGridExpandedBinding.java:86)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.lagradost.cloudstream3.ui.home.HomeChildItemAdapter.onCreateContent(HomeChildItemAdapter.kt:64)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.lagradost.cloudstream3.ui.BaseAdapter.onCreateViewHolder(BaseAdapter.kt:180)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.lagradost.cloudstream3.ui.BaseAdapter.onCreateViewHolder(BaseAdapter.kt:49)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7719)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6804)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.View.measure(View.java:25962)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7166)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.View.measure(View.java:25962)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:10124)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1688)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1158)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2009)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2108)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3826)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14571)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2821)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3255)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4199)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14838)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6438)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6239)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5712)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5770)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5736)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5901)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5744)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5958)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5717)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5770)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5736)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5744)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5717)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8669)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8620)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8586)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8800)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:335)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:161)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7941)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
05-13 02:55:17.684 23959 23959 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 87392 free bytes and 85KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at java.util.ArrayList.grow(ArrayList.java:246)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at java.util.ArrayList.grow(ArrayList.java:251)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:461)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:474)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VGroup.addChild(VectorDrawable.java:1370)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1343)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1333)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1333)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:994)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable.mutate(VectorDrawable.java:389)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:721)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable.<init>(AnimatedVectorDrawable.java:335)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable.<init>(AnimatedVectorDrawable.java:300)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.newDrawable(AnimatedVectorDrawable.java:757)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.graphics.drawable.Drawable$ConstantState.newDrawable(Drawable.java:1538)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.content.res.DrawableCache.getInstance(DrawableCache.java:45)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:645)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:993)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1007)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:982)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.widget.ProgressBar.<init>(ProgressBar.java:322)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at android.widget.ProgressBar.<init>(ProgressBar.java:270)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	at androidx.core.widget.ContentLoadingProgressBar.<init>(ContentLoadingProgressBar.java:63)
05-13 02:55:17.685 23959 23959 E AndroidRuntime: 	... 96 more
05-13 03:05:24.999 23955 17933 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17933 (MediaCodec_loop), pid 23955 (eam3.prerelease)
05-13 03:05:27.089 18526 18526 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-13 03:05:27.089 18526 18526 F DEBUG   : Native Crash TIME: 156919630
05-13 03:05:27.089 18526 18526 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-13 03:05:27.089 18526 18526 F DEBUG   : Build fingerprint: 'Symphony/Z60/Z60:12/SP1A.210812.016/160:user/release-keys'
05-13 03:05:27.089 18526 18526 F DEBUG   : Revision: '0'
05-13 03:05:27.089 18526 18526 F DEBUG   : ABI: 'arm64'
05-13 03:05:27.089 18526 18526 F DEBUG   : Timestamp: 2024-05-13 03:05:25.305910953+0600
05-13 03:05:27.089 18526 18526 F DEBUG   : Process uptime: 0s
05-13 03:05:27.089 18526 18526 F DEBUG   : Cmdline: com.lagradost.cloudstream3.prerelease
05-13 03:05:27.089 18526 18526 F DEBUG   : pid: 23955, tid: 17933, name: MediaCodec_loop  >>> com.lagradost.cloudstream3.prerelease <<<
05-13 03:05:27.089 18526 18526 F DEBUG   : uid: 10669
05-13 03:05:27.089 18526 18526 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
05-13 03:05:27.089 18526 18526 F DEBUG   : Abort message: 'No pending exception expected: java.lang.IllegalStateException: 
05-13 03:05:27.089 18526 18526 F DEBUG   : (Throwable with empty stack trace)
05-13 03:05:27.089 18526 18526 F DEBUG   : '
05-13 03:05:27.089 18526 18526 F DEBUG   :     x0  0000000000000000  x1  000000000000460d  x2  0000000000000006  x3  000000736274c1c0
05-13 03:05:27.089 18526 18526 F DEBUG   :     x4  6f646277641f666d  x5  6f646277641f666d  x6  6f646277641f666d  x7  7f7f7f7f7f7f7f7f
05-13 03:05:27.089 18526 18526 F DEBUG   :     x8  00000000000000f0  x9  f54e89390770def7  x10 0000000000000000  x11 ffffff80fffffb9f
05-13 03:05:27.089 18526 18526 F DEBUG   :     x12 0000000000000001  x13 0000000000000095  x14 000000736274afc0  x15 0000000026762762
05-13 03:05:27.089 18526 18526 F DEBUG   :     x16 00000076ad522050  x17 00000076ad4ffb00  x18 000000727e73e000  x19 0000000000005d93
05-13 03:05:27.089 18526 18526 F DEBUG   :     x20 000000000000460d  x21 00000000ffffffff  x22 0000000000000000  x23 00000074016a922c
05-13 03:05:27.089 18526 18526 F DEBUG   :     x24 0000000000000000  x25 0000007402213000  x26 b400007425e2bd20  x27 0000007402216000
05-13 03:05:27.089 18526 18526 F DEBUG   :     x28 0000007402216000  x29 000000736274c240
05-13 03:05:27.089 18526 18526 F DEBUG   :     lr  00000076ad4b27a4  sp  000000736274c1a0  pc  00000076ad4b27d0  pst 0000000000000000
05-13 03:05:27.089 18526 18526 F DEBUG   : backtrace:
05-13 03:05:27.089 18526 18526 F DEBUG   :       #00 pc 000000000004f7d0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 5d21548447ff2f9aab8359665aaabf4f)
05-13 03:05:27.089 18526 18526 F DEBUG   :       #01 pc 000000000076fde0  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+904) (BuildId: 7ece79c15d80914c83e60c9e93ac1684)
05-13 03:05:27.089 18526 18526 F DEBUG   :       #02 pc 00000000000357d0  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
05-13 03:05:27.089 18526 18526 F DEBUG   :       #03 pc 0000000000034d58  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
05-13 03:05:27.089 18526 18526 F DEBUG   :       #04 pc 000000000025aa50  /apex/com.android.art/lib64/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+8988) (BuildId: 7ece79c15d80914c83e60c9e93ac1684)
05-13 03:05:27.089 18526 18
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by EHMilon** [comment]
> Can I know which provider you're using? I can't download even if I play it first. A cross just appear on the download button when trying to download but nothing happens after that. I'm on latest pre-release build and CodeStream provider.

Usually I used many providers for download movies and tv series. On of them are SoraStream, Cinezone, SupperStream.

**Comment by EHMilon** [comment]
> I fixed my problem actually, turns out when I used a custom download path, it wouldn't download. 

But it didn't work for me?
