### ISSUE TITLE
Battery drain while app in the background or screen off 

### ISSUE THREAD

**Issue by Morset1** [recloudstream/cloudstream#1373]
### Steps to reproduce

-Phone fully charged
-Run the app and play any video for couple seconds.
-Turn off screen
-sleep for 8 hours 

### Expected behavior

The battery should be at least at 90-95%

### Actual behavior

The battery is at most 20-30%

### Cloudstream version and commit hash

4.4.0 15a27b4 

### Android version

11

### Logcat

```java
--------- beginning of main
10-11 23:48:14.070 18799 18799 I CS3ExoPlayer: SET STYLE = SaveCaptionStyle(foregroundColor=-1, backgroundColor=0, windowColor=0, edgeType=1, edgeColor=-16777216, typeface=null, typefaceFilePath=null, elevation=20, fixedTextSize=null, removeCaptions=false, removeBloat=true, upperCase=false)
10-11 23:48:14.083 18799 18842 I SYNCVM  : addFromUrl = https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:14.083 18799 18842 I SYNCUTIL: getIdsFromUrl https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:14.100 18799 18799 I CS3ExoPlayer: reloadPlayer
10-11 23:48:14.100 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:14.109 18799 18799 W View    : requestLayout() improperly called by android.widget.FrameLayout{a85742e I.E..V... ......I. 0,0-0,0 #7f0a04d7 app:id/start_panel} during layout: running second layout pass
10-11 23:48:14.110 18799 18799 W View    : requestLayout() improperly called by android.widget.FrameLayout{68f3684 I.E..V... ......ID 1080,0-1080,1562 #7f0a0167 app:id/end_panel} during layout: running second layout pass
10-11 23:48:15.895 18799 18842 I RVM2    : applyMeta
10-11 23:48:16.292 18799 18799 W PanelsChildGestureRegionObserver: failed to register view with ID 2131362786. already registered
10-11 23:48:16.328 18799 18799 I SYNCVM  : addSync mal = 55823
10-11 23:48:16.328 18799 18799 I SYNCVM  : addSync anilist = 166611
10-11 23:48:16.328 18799 18799 I SYNCVM  : updateMetaAndUser
10-11 23:48:16.329 18799 18799 I SYNCVM  : updateSynced
10-11 23:48:16.329 18799 18848 I SYNCVM  : updateMetadata
10-11 23:48:16.329 18799 18843 I SYNCVM  : updateUserData
10-11 23:48:16.329 18799 18848 I SYNCVM  : updateMetadata loading anilist
10-11 23:48:16.594 18799 18799 I SYNCVM  : setScore = 0
10-11 23:48:16.595 18799 18799 I SYNCVM  : setEpisodes = 0
10-11 23:48:16.615 18799 18799 I RVM2    : setMeta
10-11 23:48:16.617 18799 18839 I RVM2    : applyMeta
10-11 23:48:17.126 18799 18813 I eam3.prereleas: Background young concurrent copying GC freed 497122(17MB) AllocSpace objects, 28(3472KB) LOS objects, 29% free, 52MB/73MB, paused 1.087ms total 121.823ms
10-11 23:48:17.310 18799 18799 W PanelsChildGestureRegionObserver: failed to register view with ID 2131362786. already registered
10-11 23:48:17.336 18799 18839 I SYNCVM  : addFromUrl = https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:17.336 18799 18839 I SYNCUTIL: getIdsFromUrl https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:18.867 18799 18799 I RepoLink: goto 0
10-11 23:48:18.867 18799 18799 I CS3ExoPlayer: newInstance = {anilist=166611, mal=55823}
10-11 23:48:18.871 18799 18799 I CS3ExoPlayer: onStop
10-11 23:48:18.871 18799 18799 I CS3ExoPlayer: saveData
10-11 23:48:18.871 18799 18799 I CS3ExoPlayer: handleEvent Pause
10-11 23:48:18.872 18799 18799 I CS3ExoPlayer: unwrapBundle = null
10-11 23:48:18.873 18799 18799 I CS3ExoPlayer: unwrapBundle = Bundle[{resumePosition=0, syncData={anilist=166611, mal=55823}}]
10-11 23:48:18.873 18799 18799 I SYNCVM  : addSync anilist = 166611
10-11 23:48:18.873 18799 18799 I SYNCVM  : addSync mal = 55823
10-11 23:48:18.920 18799 18799 I CS3ExoPlayer: SET STYLE = SaveCaptionStyle(foregroundColor=-1, backgroundColor=0, windowColor=0, edgeType=1, edgeColor=-16777216, typeface=null, typefaceFilePath=null, elevation=20, fixedTextSize=null, removeCaptions=false, removeBloat=true, upperCase=false)
10-11 23:48:18.931 18799 18799 I CS3ExoPlayer: unwrapBundle = null
10-11 23:48:18.931 18799 18799 I CS3ExoPlayer: unwrapBundle = Bundle[{resumePosition=0, syncData={anilist=166611, mal=55823}}]
10-11 23:48:18.931 18799 18839 I SYNCVM  : updateUserData
10-11 23:48:18.931 18799 18799 I PlayViewGen: loadLinks
10-11 23:48:18.932 18799 18799 I CS3ExoPlayer: setActiveSubtitles 0
10-11 23:48:18.932 18799 18799 I CS3ExoPlayer: autoSelectFromSettings = null
10-11 23:48:19.247 18799 18799 I CS3ExoPlayer: reloadPlayer
10-11 23:48:19.247 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:19.378 18799 18799 I CS3ExoPlayer: setActiveSubtitles 0
10-11 23:48:19.378 18799 18799 I CS3ExoPlayer: autoSelectFromSettings = null
10-11 23:48:19.378 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:20.799 18799 18843 D ApiError: -------------------------------------------------------------------
10-11 23:48:20.799 18799 18843 D ApiError: safeApiCall: Invalid symbol '\'(134) at index 160
10-11 23:48:20.799 18799 18843 D ApiError: safeApiCall: Invalid symbol '\'(134) at index 160
10-11 23:48:20.799 18799 18843 W System.err: java.lang.IllegalArgumentException: Invalid symbol '\'(134) at index 160
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.io.encoding.Base64.decodeImpl(Base64.kt:373)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.io.encoding.Base64.decode(Base64.kt:156)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.io.encoding.Base64.decode$default(Base64.kt:150)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.io.encoding.Base64.decode(Base64.kt:218)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.io.encoding.Base64.decode$default(Base64.kt:216)
10-11 23:48:20.799 18799 18843 W System.err: 	at com.lagradost.cloudstream3.MainAPIKt.base64DecodeArray(MainAPI.kt:557)
10-11 23:48:20.799 18799 18843 W System.err: 	at com.lagradost.cloudstream3.extractors.helper.GogoHelper.cryptoHandler(GogoHelper.kt:48)
10-11 23:48:20.799 18799 18843 W System.err: 	at com.lagradost.cloudstream3.extractors.helper.GogoHelper.access$cryptoHandler(GogoHelper.kt:20)
10-11 23:48:20.799 18799 18843 W System.err: 	at com.lagradost.cloudstream3.extractors.helper.GogoHelper$extractVidstream$2.invokeSuspend(GogoHelper.kt:112)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-11 23:48:20.799 18799 18843 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
10-11 23:48:20.800 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
10-11 23:48:20.800 18799 18843 D ApiError: -------------------------------------------------------------------
10-11 23:48:24.061 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=StreamWish, url=https://r63hfpdmodtc.pradoi.com/hls2/01/05079/d1is5wtuhj64_,l,n,h,.urlset/index-f1-v1-a1.m3u8?t=QvrERUvqxDphJ2vYZUYQBZFa1UYhfhHQQt3HuuBRBlM&s=1728679702&e=129600&f=25397765&srv=xhisossxof6ziadr&i=0.0&sp=500&p1=xhisossxof6ziadr&p2=xhisossxof6ziadr&asn=48832, referer=https://awish.pro, type=M3U8)
10-11 23:48:24.062 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=StreamWish, url=https://r63hfpdmodtc.pradoi.com/hls2/01/05079/d1is5wtuhj64_,l,n,h,.urlset/index-f2-v1-a1.m3u8?t=QvrERUvqxDphJ2vYZUYQBZFa1UYhfhHQQt3HuuBRBlM&s=1728679702&e=129600&f=25397765&srv=xhisossxof6ziadr&i=0.0&sp=500&p1=xhisossxof6ziadr&p2=xhisossxof6ziadr&asn=48832, referer=https://awish.pro, type=M3U8)
10-11 23:48:24.062 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=StreamWish, url=https://r63hfpdmodtc.pradoi.com/hls2/01/05079/d1is5wtuhj64_,l,n,h,.urlset/index-f3-v1-a1.m3u8?t=QvrERUvqxDphJ2vYZUYQBZFa1UYhfhHQQt3HuuBRBlM&s=1728679702&e=129600&f=25397765&srv=xhisossxof6ziadr&i=0.0&sp=500&p1=xhisossxof6ziadr&p2=xhisossxof6ziadr&asn=48832, referer=https://awish.pro, type=M3U8)
10-11 23:48:24.062 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=StreamWish, url=https://r63hfpdmodtc.pradoi.com/hls2/01/05079/d1is5wtuhj64_,l,n,h,.urlset/master.m3u8?t=QvrERUvqxDphJ2vYZUYQBZFa1UYhfhHQQt3HuuBRBlM&s=1728679702&e=129600&f=25397765&srv=xhisossxof6ziadr&i=0.0&sp=500&p1=xhisossxof6ziadr&p2=xhisossxof6ziadr&asn=48832, referer=https://awish.pro, type=M3U8)
10-11 23:48:24.598 18799 18843 D ApiError: -------------------------------------------------------------------
10-11 23:48:24.599 18799 18843 D ApiError: safeApiCall: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
10-11 23:48:24.599 18799 18843 D ApiError: safeApiCall: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
10-11 23:48:24.599 18799 18843 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
10-11 23:48:24.599 18799 18843 W System.err: 	at java.util.regex.Matcher.reset(Matcher.java:256)
10-11 23:48:24.599 18799 18843 W System.err: 	at java.util.regex.Matcher.<init>(Matcher.java:167)
10-11 23:48:24.599 18799 18843 W System.err: 	at java.util.regex.Pattern.matcher(Pattern.java:1027)
10-11 23:48:24.599 18799 18843 W System.err: 	at com.lagradost.cloudstream3.utils.JsUnpacker.unpack(JsUnpacker.kt:33)
10-11 23:48:24.599 18799 18843 W System.err: 	at com.lagradost.cloudstream3.utils.ExtractorApiKt.getAndUnpack(ExtractorApi.kt:639)
10-11 23:48:24.599 18799 18843 W System.err: 	at com.lagradost.cloudstream3.extractors.Mp4Upload.getUrl$suspendImpl(Mp4Upload.kt:22)
10-11 23:48:24.599 18799 18843 W System.err: 	at com.lagradost.cloudstream3.extractors.Mp4Upload$getUrl$1.invokeSuspend(Unknown Source:15)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
10-11 23:48:24.599 18799 18843 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
10-11 23:48:24.599 18799 18843 D ApiError: -------------------------------------------------------------------
10-11 23:48:24.600 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=Mp4Upload, url=https://www6.mp4upload.com:183/d/sgxs3amjz3b4quuop2raap2kcjcus725k3oj4k5c7zjai2yas72alijgzl6brv7dsrsevww3/video.mp4, referer=https://www.mp4upload.com/embed-zmj37kf1w8bc.html, type=VIDEO)
10-11 23:48:25.225 18799 18843 D RepoLink: Loaded ExtractorLink: ExtractorLink(name=DoodStream, url=https://oi321o.cloudatacdn.com/u5kj7px7spclsdgge4goqzabdv5l627niyzptc3wlgth6odylgiysikkxi5a/9rf9uu3die~vOA2P0cf7h?token=q7wpbhhraxl5wn5ea8tq43ib, referer=https://dood.wf/, type=VIDEO)
10-11 23:48:25.230 18799 18799 I CS3ExoPlayer: loadPlayer
10-11 23:48:25.230 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:25.250 18799 18799 I CS3ExoPlayer: loadOnlinePlayer ExtractorLink(name=DoodStream, url=https://oi321o.cloudatacdn.com/u5kj7px7spclsdgge4goqzabdv5l627niyzptc3wlgth6odylgiysikkxi5a/9rf9uu3die~vOA2P0cf7h?token=q7wpbhhraxl5wn5ea8tq43ib, referer=https://dood.wf/, type=VIDEO)
10-11 23:48:25.251 18799 18848 I PreviewImgMp4: Loading with url = https://oi321o.cloudatacdn.com/u5kj7px7spclsdgge4goqzabdv5l627niyzptc3wlgth6odylgiysikkxi5a/9rf9uu3die~vOA2P0cf7h?token=q7wpbhhraxl5wn5ea8tq43ib headers = {referer=https://dood.wf/}
10-11 23:48:25.251 18799 18848 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@5e9dda): Cookies: null
10-11 23:48:25.259 18799 18848 V MediaHTTPService: makeHTTPConnection: CookieManager created: java.net.CookieManager@cfdd20b
10-11 23:48:25.259 18799 18848 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@5e9dda): cookieHandler: java.net.CookieManager@cfdd20b Cookies: null
10-11 23:48:25.272 18799 18799 I CS3ExoPlayer: loadExo
10-11 23:48:25.287 18799 18799 I ExoPlayerImpl: Init d93f8e8 [AndroidXMedia3/1.4.1] [jd2019, Lenovo Z5s, lenovo, 30]
10-11 23:48:25.302 18799 18799 I DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
10-11 23:48:25.320 18799 18799 I CS3ExoPlayer: Handle event: PlayerAttachedEvent(player=androidx.media3.exoplayer.ExoPlayerImpl@d93f8e8, source=Player)
10-11 23:48:25.324 18799 18799 I MediaSessionImpl: Init b23bb94 [AndroidXMedia3/1.4.1] [jd2019, Lenovo Z5s, lenovo, 30]
10-11 23:48:25.353 18799 18799 I CS3ExoPlayer: Handle event: StatusEvent(wasPlaying=IsBuffering, isPlaying=IsBuffering, source=Player)
10-11 23:48:25.356 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=0, toMs=0, durationMs=-9223372036854775807)
10-11 23:48:25.357 18799 18799 I CS3ExoPlayer: setActiveSubtitles 0
10-11 23:48:25.357 18799 18799 I CS3ExoPlayer: autoSelectFromSettings = null
10-11 23:48:26.314 18799 19452 W Utils   : could not parse long range '484-472'
10-11 23:48:26.315 18799 19452 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
10-11 23:48:26.315 18799 19452 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
10-11 23:48:26.344 18799 18848 I PreviewImgMp4: Started loading preview
10-11 23:48:26.350 18799 18848 I PreviewImgMp4: Generating preview for 50.0%
10-11 23:48:26.375 18799 18799 I CS3ExoPlayer: Handle event: EmbeddedSubtitlesFetchedEvent(tracks=[], source=Player)
10-11 23:48:26.375 18799 18799 I CS3ExoPlayer: Handle event: TracksChangedEvent(source=Player)
10-11 23:48:26.376 18799 18799 I CS3ExoPlayer: Handle event: SubtitlesUpdatedEvent(source=Player)
10-11 23:48:26.385 18799 19463 I OMXClient: IOmx service obtained
10-11 23:48:26.545 18799 18813 I eam3.prereleas: Background concurrent copying GC freed 563036(23MB) AllocSpace objects, 62(8944KB) LOS objects, 51% free, 44MB/92MB, paused 100us total 259.015ms
10-11 23:48:26.550 18799 19461 D SurfaceUtils: connecting to surface 0x72911ae3a0, reason connectToSurface
10-11 23:48:26.551 18799 19461 I MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 19250177
10-11 23:48:26.551 18799 19461 D SurfaceUtils: disconnecting from surface 0x72911ae3a0, reason connectToSurface(reconnect)
10-11 23:48:26.551 18799 19461 D SurfaceUtils: connecting to surface 0x72911ae3a0, reason connectToSurface(reconnect)
10-11 23:48:26.595 18799 19463 D SurfaceUtils: set up nativeWindow 0x72911ae3a0 for 1920x1080, color 0x7fa30c06, rotation 0, usage 0x20002900
10-11 23:48:26.667 18799 18799 I CS3ExoPlayer: Handle event: ResizedEvent(height=1080, width=1920, source=Player)
10-11 23:48:26.669 18799 18799 I CS3ExoPlayer: Rendered first frame
10-11 23:48:26.670 18799 18799 I CS3ExoPlayer: setPreferredSubtitles init null
10-11 23:48:26.670 18799 18799 I CS3ExoPlayer: Handle event: ResizedEvent(height=1080, width=1920, source=Player)
10-11 23:48:26.672 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=0, toMs=0, durationMs=1430071)
10-11 23:48:26.673 18799 18843 I EpisodeSkip: Requesting SkipStamp from {mal=55823, anilist=166611}
10-11 23:48:26.673 18799 18843 I AniSkip : Requesting https://api.aniskip.com/v2/skip-times/55823/1?types[]=ed&types[]=mixed-ed&types[]=mixed-op&types[]=op&types[]=recap&episodeLength=1430
10-11 23:48:26.684 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=0, toMs=0, durationMs=1430071)
10-11 23:48:26.699 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=0, toMs=0, durationMs=1430071)
10-11 23:48:26.713 18799 18799 I CS3ExoPlayer: Handle event: StatusEvent(wasPlaying=IsPaused, isPlaying=IsPlaying, source=Player)
10-11 23:48:26.720 18799 18799 I CS3ExoPlayer: Handle event: RequestAudioFocusEvent(source=Player)
10-11 23:48:26.766 18799 19452 D AudioTrack: getTimestamp_l(1460): device stall time corrected using current time 41316623146998
10-11 23:48:27.185 18799 18843 I AniSkip : Found false with 0 results
10-11 23:48:27.186 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=426, toMs=426, durationMs=1430071)
10-11 23:48:27.899 18799 18848 I PreviewImgMp4: Generating preview for 25.0%
10-11 23:48:28.605 18799 18799 I CS3ExoPlayer: onStop
10-11 23:48:28.605 18799 18799 I CS3ExoPlayer: saveData
10-11 23:48:28.605 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=1844, toMs=1844, durationMs=1430071)
10-11 23:48:28.610 18799 18799 I CS3ExoPlayer: handleEvent Pause
10-11 23:48:28.610 18799 18799 I CS3ExoPlayer: Handle event: PauseEvent(source=Player)
10-11 23:48:28.611 18799 18799 I CS3ExoPlayer: Handle event: StatusEvent(wasPlaying=IsPlaying, isPlaying=IsPaused, source=Player)
10-11 23:48:28.828 18799 18799 I CS3ExoPlayer: SET STYLE = SaveCaptionStyle(foregroundColor=-1, backgroundColor=0, windowColor=0, edgeType=1, edgeColor=-16777216, typeface=null, typefaceFilePath=null, elevation=20, fixedTextSize=null, removeCaptions=false, removeBloat=true, upperCase=false)
10-11 23:48:28.846 18799 18843 I SYNCVM  : addFromUrl = https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:28.846 18799 18843 I SYNCUTIL: getIdsFromUrl https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:28.975 18799 18799 I SYNCVM  : setEpisodes = 0
10-11 23:48:28.976 18799 18799 I SYNCVM  : setScore = 0
10-11 23:48:29.003 18799 18842 I SYNCVM  : addFromUrl = https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:29.003 18799 18842 I SYNCUTIL: getIdsFromUrl https://anitaku.to/category/natsume-yuujinchou-shichi
10-11 23:48:29.004 18799 18799 I RVM2    : setMeta same
10-11 23:48:29.018 18799 18799 I CS3ExoPlayer: reloadPlayer
10-11 23:48:29.018 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:29.137 18799 18848 I PreviewImgMp4: Generating preview for 75.0%
10-11 23:48:29.145 18799 18799 W View    : requestLayout() improperly called by android.widget.FrameLayout{948e608 I.E..V... ......I. 0,0-0,0 #7f0a04d7 app:id/start_panel} during layout: running second layout pass
10-11 23:48:29.145 18799 18799 W View    : requestLayout() improperly called by android.widget.FrameLayout{d3f3091 I.E..V... ......ID 553,0-1080,1705 #7f0a0167 app:id/end_panel} during layout: running second layout pass
10-11 23:48:29.261 18799 19461 D SurfaceUtils: connecting to surface 0x729118c2a0, reason connectToSurface
10-11 23:48:29.261 18799 19461 I MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 19250178
10-11 23:48:29.261 18799 19461 D SurfaceUtils: disconnecting from surface 0x729118c2a0, reason connectToSurface(reconnect)
10-11 23:48:29.261 18799 19461 D SurfaceUtils: connecting to surface 0x729118c2a0, reason connectToSurface(reconnect)
10-11 23:48:29.262 18799 19463 D SurfaceUtils: set up nativeWindow 0x729118c2a0 for 1920x1088, color 0x7fa30c06, rotation 0, usage 0x20002900
10-11 23:48:29.262 18799 19461 D SurfaceUtils: disconnecting from surface 0x72911ae3a0, reason disconnectFromSurface
10-11 23:48:29.262 18799 19461 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
10-11 23:48:29.266 18799 18843 I SYNCVM  : updateUserData
10-11 23:48:29.269 18799 18799 I CS3ExoPlayer: releasePlayer
10-11 23:48:29.269 18799 18799 I CS3ExoPlayer: Handle event: PositionEvent(source=Player, fromMs=1853, toMs=1853, durationMs=1430071)
10-11 23:48
```

### Other details

This issue has been ongoing for over a month.
 I have never experienced this problem in the past two years of using this app on the same OS.

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CranberrySoup** [comment]
What does android settings say? It tracks battery usage by app
